[deploy]
bucket = 'avn-cfn-artifacts'
region = 'ap-south-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'amitnike/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "avn-codepipeline-cruddur-artifacts"